### PR TITLE
AUI-2037

### PR DESCRIPTION
**Pull request by blzaugg**

### CODE REVIEW

**Comment by blzaugg** [comment]
@peterborkuti, please retest this. If all is good, you can send this to @jonmak08.

There was a few issues with your CSS. I also removed some source formatting changes, to keep it in line for 2.0.x.

**Comment by peterborkuti** [comment]
Hi @blzaugg,

This is a screenshot from my backport:
image


And this is after thesting your branch:
image

I think, there are three issues here (which were fixed in my backport) see the yellow circles:
* unaligned checkbox
* not red bordered not-unique value fileds
* alert message is not red

May I missing something? Did I create a bad build or did I used the wrong branch?

**Comment by blzaugg** [comment]
I was using `$ grunt all` to build. I didn't have these CSS issues. I will test it again.

One note, when I built yours, it did not look like the first image.

**Comment by blzaugg** [comment]
This is what I get with my fix:
fixed-ie-ff-chrome

This is what I get with your fix:
broken-ie-ff-chrome

Also note, your buttons look a little off. I'm guessing you're missing some other CSS as well.

@jonmak08 can you test this?

**Comment by jonmak08** [comment]
Hey guys,

This is what I see:

Chrome:
image

Firefox:
image

Safari:
image

**Comment by jonmak08** [comment]
Hey guys,

This is what I see from @peterborkuti's original pull request (https://github.com/blzaugg/alloy-ui/pull/63) to @blzaugg.

Chrome:
image

Firefox:
image

Safari:
image

**Comment by peterborkuti** [comment]
Hi, thanks for testing.

There should be something bad here in my PC when I build Alloy, probably with compass.
I am checking this.

Because of the time limit, could you left me out from the process and could @jonmak08 take care of this instead of me?

Thank you in advance
Péter

**Comment by peterborkuti** [comment]
I forwarded it to Jon:
https://github.com/jonmak08/alloy-ui/pull/331

**Pull request closed without merging**
